"""Public Synth optimizer package.

The HTTP service (`gepa_serve`) is the public surface. Raw worker/workspace
PyO3 exports were demoted in the v2 service rebuild and are no longer importable.
"""

from ._synth_optimizers import (
    BudgetExceededError,
    CacheCorruptError,
    CacheFullError,
    CacheMissError,
    CancelledError,
    ConfigError,
    ContainerContractError,
    EventCompareError,
    GepaRunResult,
    InvariantError,
    OptimizerDiskBudgetError,
    OptimizerHttpError,
    OptimizerIoError,
    OptimizerJsonError,
    OptimizerSqliteError,
    OptimizerTomlDecodeError,
    ProposerError,
    RunFailedError,
    StateTransitionError,
    SynthOptimizerError,
    __version__,
    events_compare,
    events_replay,
    gepa_serve,
)
from .gepa import (
    BudgetConfig,
    CacheConfig,
    GepaBudgetConfig,
    GepaConfig,
    GepaDefaults,
    GepaPipeline,
    GepaPipelineMode,
    GepaRun,
    GepaStalenessPolicy,
    ObjectiveConfig,
    OutputConfig,
    PolicyConfig,
    PolicyType,
    ProposerDefaults,
    ProposerConfig,
    ProposerPromptConfig,
    RunSettings,
    TasksetSelection,
)
from .sdk import OptimizerConfig, OptimizerRun

__all__ = [
    "BudgetExceededError",
    "CacheCorruptError",
    "CacheFullError",
    "CacheMissError",
    "CancelledError",
    "ConfigError",
    "ContainerContractError",
    "EventCompareError",
    "BudgetConfig",
    "CacheConfig",
    "GepaBudgetConfig",
    "GepaConfig",
    "GepaDefaults",
    "GepaPipeline",
    "GepaPipelineMode",
    "GepaRun",
    "GepaRunResult",
    "GepaStalenessPolicy",
    "InvariantError",
    "ObjectiveConfig",
    "OptimizerConfig",
    "OptimizerRun",
    "OptimizerDiskBudgetError",
    "OptimizerHttpError",
    "OptimizerIoError",
    "OptimizerJsonError",
    "OptimizerSqliteError",
    "OptimizerTomlDecodeError",
    "OutputConfig",
    "PolicyConfig",
    "PolicyType",
    "ProposerDefaults",
    "ProposerError",
    "ProposerConfig",
    "ProposerPromptConfig",
    "RunFailedError",
    "RunSettings",
    "StateTransitionError",
    "SynthOptimizerError",
    "TasksetSelection",
    "__version__",
    "events_compare",
    "events_replay",
    "gepa_serve",
]
