"""Public Synth optimizer package.

The HTTP service (`gepa_serve`) is the public surface. Raw worker/workspace
PyO3 exports were demoted in the v2 service rebuild and are no longer importable.
"""

import importlib
from typing import Any

from ._synth_optimizers import (
    BudgetExceededError,
    CacheCorruptError,
    CacheFullError,
    CacheMissError,
    CancelledError,
    ConfigError,
    ContainerContractError,
    EventCompareError,
    GepaRunResult,
    InvariantError,
    OptimizerDiskBudgetError,
    OptimizerHttpError,
    OptimizerIoError,
    OptimizerJsonError,
    OptimizerSqliteError,
    OptimizerTomlDecodeError,
    ProposerError,
    RunFailedError,
    StateTransitionError,
    SynthOptimizerError,
    __version__,
    events_compare,
    events_replay,
    gepa_compact_run_storage,
    gepa_delete_run_storage,
    gepa_serve,
)
from .gelo import (
    GeloCacheMode,
    GeloCacheSection,
    GeloCheckpointSemantics,
    GeloContainerSection,
    GeloDiskBudgetSection,
    GeloEngineSection,
    GeloHostedConfig,
    GeloMaterializeError,
    GeloMaterializer,
    GeloPluginKind,
    GeloPluginSection,
    GeloPluginsSection,
    GeloPolicySection,
    GeloPreset,
    GeloPresetName,
    GeloProposerRole,
    GeloProposerSection,
    GeloRewardMode,
    GeloRunSection,
    GeloSeedCandidateSection,
    GeloTasksetSection,
)
from .hosted import (
    AlgorithmCatalogEntry,
    AlgorithmCatalogStatus,
    ContainerPoolTarget,
    ContainerTargetKind,
    HostedOptimizerClient,
    HostedOptimizerError,
    OptimizerBillingFeatureConfig,
    OptimizerAlgorithmSlug,
    OptimizerRunRecord,
    OptimizerRunSubmitResponse,
    OptimizerStartupCatalog,
    RunStatus as HostedRunStatus,
)
from .o11y import (
    LiveProgress,
    RegistryRecord,
    RunBoard,
    RunFailure,
    RunState,
    RunStatus,
    RunUsage,
    project_run_events,
)
from .sdk import OptimizerConfig, OptimizerRun
from .tunnels import (
    CloudflaredTunnelLease,
    ContainerDirectTarget,
    ManagedTunnelLease,
    NgrokTunnelLease,
    SynthTunnelLease,
    TunnelError,
    TunnelLease,
    TunnelLocalTarget,
    TunnelProvider,
)

_GEPA_EXPORTS = {
    "BudgetConfig",
    "CacheConfig",
    "GepaBudgetConfig",
    "GepaConfig",
    "GepaDefaults",
    "GepaPipeline",
    "GepaPipelineMode",
    "GepaRun",
    "GepaStalenessPolicy",
    "GepaTaskPools",
    "ObjectiveConfig",
    "OutputConfig",
    "PolicyConfig",
    "PolicyType",
    "ProposerConfig",
    "ProposerDefaults",
    "ProposerPromptConfig",
    "RunSettings",
    "TasksetSelection",
    "UsageRegistrationConfig",
}


def __getattr__(name: str) -> Any:
    if name not in _GEPA_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        gepa_module = importlib.import_module(".gepa", __name__)
    except ImportError as exc:
        raise ImportError(
            f"synth_optimizers.{name} requires the local GEPA runtime dependencies; "
            "install the package with the matching synth-containers version"
        ) from exc
    value = getattr(gepa_module, name)
    globals()[name] = value
    return value


__all__ = [
    "BudgetExceededError",
    "CacheCorruptError",
    "CacheFullError",
    "CacheMissError",
    "CancelledError",
    "CloudflaredTunnelLease",
    "ConfigError",
    "ContainerContractError",
    "EventCompareError",
    "BudgetConfig",
    "CacheConfig",
    "GepaBudgetConfig",
    "GepaConfig",
    "GepaDefaults",
    "GepaPipeline",
    "GepaPipelineMode",
    "GepaRun",
    "GepaRunResult",
    "GepaStalenessPolicy",
    "GepaTaskPools",
    "GeloCacheMode",
    "GeloCacheSection",
    "GeloCheckpointSemantics",
    "GeloContainerSection",
    "GeloDiskBudgetSection",
    "GeloEngineSection",
    "GeloHostedConfig",
    "GeloMaterializeError",
    "GeloMaterializer",
    "GeloPluginKind",
    "GeloPluginSection",
    "GeloPluginsSection",
    "GeloPolicySection",
    "GeloPreset",
    "GeloPresetName",
    "GeloProposerRole",
    "GeloProposerSection",
    "GeloRewardMode",
    "GeloRunSection",
    "GeloSeedCandidateSection",
    "GeloTasksetSection",
    "AlgorithmCatalogEntry",
    "AlgorithmCatalogStatus",
    "ContainerDirectTarget",
    "ContainerPoolTarget",
    "ContainerTargetKind",
    "HostedOptimizerClient",
    "HostedOptimizerError",
    "HostedRunStatus",
    "InvariantError",
    "LiveProgress",
    "ObjectiveConfig",
    "OptimizerConfig",
    "OptimizerAlgorithmSlug",
    "OptimizerBillingFeatureConfig",
    "OptimizerRun",
    "OptimizerRunRecord",
    "OptimizerRunSubmitResponse",
    "OptimizerStartupCatalog",
    "OptimizerDiskBudgetError",
    "OptimizerHttpError",
    "OptimizerIoError",
    "OptimizerJsonError",
    "OptimizerSqliteError",
    "OptimizerTomlDecodeError",
    "OutputConfig",
    "PolicyConfig",
    "PolicyType",
    "ProposerDefaults",
    "ProposerError",
    "ProposerConfig",
    "ProposerPromptConfig",
    "RegistryRecord",
    "RunBoard",
    "RunFailedError",
    "RunFailure",
    "RunSettings",
    "RunState",
    "RunStatus",
    "RunUsage",
    "StateTransitionError",
    "SynthTunnelLease",
    "SynthOptimizerError",
    "TasksetSelection",
    "TunnelLease",
    "TunnelError",
    "TunnelLocalTarget",
    "TunnelProvider",
    "UsageRegistrationConfig",
    "ManagedTunnelLease",
    "NgrokTunnelLease",
    "project_run_events",
    "__version__",
    "events_compare",
    "events_replay",
    "gepa_compact_run_storage",
    "gepa_delete_run_storage",
    "gepa_serve",
]
