"""Public Synth optimizer package.

The HTTP service (`gepa_serve`) is the public surface. Raw worker/workspace
PyO3 exports were demoted in the v2 service rebuild and are no longer importable.
"""

import importlib
from importlib.metadata import PackageNotFoundError, version as distribution_version
from typing import Any

from ._synth_optimizers import (
    BudgetExceededError,
    CacheCorruptError,
    CacheFullError,
    CacheMissError,
    CancelledError,
    ConfigError,
    ContainerContractError,
    EventCompareError,
    GepaRunResult,
    InvariantError,
    OptimizerDiskBudgetError,
    OptimizerHttpError,
    OptimizerIoError,
    OptimizerJsonError,
    OptimizerSqliteError,
    OptimizerTomlDecodeError,
    ProposerError,
    RunFailedError,
    StateTransitionError,
    SynthOptimizerError,
    __version__ as _native_version,
    events_compare,
    events_replay,
    gepa_compact_run_storage,
    gepa_delete_run_storage,
    gepa_serve,
)

try:
    __version__ = distribution_version("synth-optimizers")
except PackageNotFoundError:
    __version__ = _native_version
from .gelo import (
    GeloCacheMode,
    GeloCacheSection,
    GeloCheckpointSemantics,
    GeloContainerSection,
    GeloDiskBudgetSection,
    GeloEngineSection,
    GeloJesterkyWorkflowSection,
    GeloHostedConfig,
    GeloMaterializeError,
    GeloMaterializer,
    GeloPluginKind,
    GeloPluginSection,
    GeloPluginsSection,
    GeloPolicySection,
    GeloPreset,
    GeloPresetName,
    GeloProposerRole,
    GeloProposerSection,
    GeloRewardMode,
    GeloRunSection,
    GeloSeedCandidateSection,
    GeloTasksetSection,
)
from .hosted import (
    AlgorithmCatalogEntry,
    AlgorithmCatalogStatus,
    ContainerPoolTarget,
    ContainerTargetKind,
    HostedOptimizerClient,
    HostedOptimizerError,
    HostedTrainingLaunch,
    OptimizerBillingFeatureConfig,
    OptimizerAlgorithmSlug,
    OptimizerRunRecord,
    OptimizerRunSubmitResponse,
    OptimizerStartupCatalog,
    RunStatus as HostedRunStatus,
    submit_mapo,
    submit_sft,
    submit_cispo,
    submit_ppo,
    submit_online_reflexion,
    validate_online_reflexion_evidence_notes,
)
from .checkpoints import (
    OptimizerRunArtifact,
    OptimizerRunOutputs,
    SavedLoraCheckpoint,
    SavedLoraCheckpointPage,
    SavedLoraContractError,
    SavedLoraDownload,
    SavedLoraLineage,
    SavedLoraRunPage,
    SavedLoraStorage,
    SavedLoraUploadIntent,
)
from .model_catalog import HostedTrainingModel, HostedTrainingModelCatalog
from .training import (
    BoundedTrainingCaps,
    ContainerTrainingPreflight,
    ProviderTrainingPreflight,
    TrainingClientError,
    TrainingEvent,
    TrainingLifecycle,
    TrainingRolloutRequirement,
    HostedTrainingSpec,
    RequestedTraining,
    apply_rollout_preflight,
    apply_provider_preflight,
    preflight_training_container,
    reduce_training_lifecycle,
    validate_training_capabilities,
    validate_provider_training_capabilities,
    build_hosted_training_config,
)
from .hosted_config import HostedOptimizerConfig
from .sft import (
    SFT_ALGORITHM_ID,
    BetaSftExecutorClient,
    SftArtifact,
    SftConfig,
    SftPublicServiceClient,
    SftService,
    SftServiceError,
    create_sft_http_server,
    serve_sft_service,
)
from .future_algorithms import (
    FUTURE_HOSTED_ALGORITHMS,
    FutureHostedAlgorithm,
    FutureHostedAlgorithmSlug,
)
from .o11y import (
    LiveProgress,
    RegistryRecord,
    RunBoard,
    RunFailure,
    RunState,
    RunStatus,
    RunUsage,
    project_run_events,
)
from .observability import (
    A3_TASK,
    DualGepaHub,
    InMemoryRunLog,
    LUNA_MED_PROPOSER_POLICY_REF,
    SOL_MED_PROPOSER_POLICY_REF,
    OptimizerEvent,
    OptimizerEventType,
    OptimizerItem,
    OptimizerItemType,
    OptimizerLogLevel,
    OptimizerStateSlice,
    OptimizerStateSliceKind,
    banking77_eval_policy_ref,
    container_child_eval_ref,
    gepa_proposer_policy_ref,
    optimizer_event_log_id,
    policy_ref,
    proposer_delta_payload,
)
from .sdk import OptimizerConfig, OptimizerRun
from .tunnels import (
    attach_synth_tunnel_lease,
    CloudflaredTunnelLease,
    ContainerDirectTarget,
    ManagedTunnelLease,
    NgrokTunnelLease,
    SynthTunnelLease,
    TunnelError,
    TunnelLease,
    TunnelLocalTarget,
    TunnelProvider,
)

_GEPA_EXPORTS = {
    "BudgetConfig",
    "CacheConfig",
    "GepaBudgetConfig",
    "GepaConfig",
    "GepaDefaults",
    "GepaPipeline",
    "GepaPipelineMode",
    "GepaRun",
    "GepaStalenessPolicy",
    "GepaTaskPools",
    "ObjectiveConfig",
    "OutputConfig",
    "PolicyConfig",
    "PolicyType",
    "ProposerConfig",
    "ProposerDefaults",
    "ProposerPromptConfig",
    "RunSettings",
    "TasksetSelection",
    "UsageRegistrationConfig",
}


def __getattr__(name: str) -> Any:
    if name not in _GEPA_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        gepa_module = importlib.import_module(".gepa", __name__)
    except ImportError as exc:
        raise ImportError(
            f"synth_optimizers.{name} requires the local GEPA runtime dependencies; "
            "install the package with the matching synth-containers version"
        ) from exc
    value = getattr(gepa_module, name)
    globals()[name] = value
    return value


__all__ = [
    "BudgetExceededError",
    "CacheCorruptError",
    "CacheFullError",
    "CacheMissError",
    "A3_TASK",
    "CancelledError",
    "CloudflaredTunnelLease",
    "ConfigError",
    "container_child_eval_ref",
    "ContainerContractError",
    "DualGepaHub",
    "EventCompareError",
    "BudgetConfig",
    "CacheConfig",
    "GepaBudgetConfig",
    "GepaConfig",
    "GepaDefaults",
    "GepaPipeline",
    "GepaPipelineMode",
    "GepaRun",
    "GepaRunResult",
    "GepaStalenessPolicy",
    "GepaTaskPools",
    "GeloCacheMode",
    "GeloCacheSection",
    "GeloCheckpointSemantics",
    "GeloContainerSection",
    "GeloDiskBudgetSection",
    "GeloEngineSection",
    "GeloJesterkyWorkflowSection",
    "GeloHostedConfig",
    "GeloMaterializeError",
    "GeloMaterializer",
    "GeloPluginKind",
    "GeloPluginSection",
    "GeloPluginsSection",
    "GeloPolicySection",
    "GeloPreset",
    "GeloPresetName",
    "GeloProposerRole",
    "GeloProposerSection",
    "GeloRewardMode",
    "GeloRunSection",
    "GeloSeedCandidateSection",
    "GeloTasksetSection",
    "AlgorithmCatalogEntry",
    "AlgorithmCatalogStatus",
    "ContainerDirectTarget",
    "ContainerPoolTarget",
    "ContainerTargetKind",
    "HostedOptimizerClient",
    "HostedOptimizerError",
    "HostedTrainingLaunch",
    "HostedTrainingModel",
    "HostedTrainingModelCatalog",
    "SavedLoraCheckpoint",
    "SavedLoraCheckpointPage",
    "SavedLoraContractError",
    "SavedLoraDownload",
    "SavedLoraLineage",
    "SavedLoraRunPage",
    "SavedLoraStorage",
    "SavedLoraUploadIntent",
    "HostedOptimizerConfig",
    "ContainerTrainingPreflight",
    "ProviderTrainingPreflight",
    "TrainingClientError",
    "TrainingEvent",
    "TrainingLifecycle",
    "TrainingRolloutRequirement",
    "apply_rollout_preflight",
    "apply_provider_preflight",
    "preflight_training_container",
    "BoundedTrainingCaps",
    "HostedTrainingSpec",
    "RequestedTraining",
    "build_hosted_training_config",
    "reduce_training_lifecycle",
    "validate_training_capabilities",
    "validate_provider_training_capabilities",
    "SFT_ALGORITHM_ID",
    "BetaSftExecutorClient",
    "SftArtifact",
    "SftConfig",
    "SftPublicServiceClient",
    "SftService",
    "SftServiceError",
    "create_sft_http_server",
    "serve_sft_service",
    "FUTURE_HOSTED_ALGORITHMS",
    "FutureHostedAlgorithm",
    "FutureHostedAlgorithmSlug",
    "HostedRunStatus",
    "InvariantError",
    "InMemoryRunLog",
    "LUNA_MED_PROPOSER_POLICY_REF",
    "LiveProgress",
    "ObjectiveConfig",
    "OptimizerConfig",
    "OptimizerAlgorithmSlug",
    "OptimizerBillingFeatureConfig",
    "OptimizerEvent",
    "OptimizerEventType",
    "OptimizerItem",
    "OptimizerItemType",
    "OptimizerLogLevel",
    "OptimizerRun",
    "OptimizerRunRecord",
    "OptimizerRunArtifact",
    "OptimizerRunOutputs",
    "OptimizerRunSubmitResponse",
    "OptimizerStateSlice",
    "OptimizerStateSliceKind",
    "OptimizerStartupCatalog",
    "OptimizerDiskBudgetError",
    "OptimizerHttpError",
    "OptimizerIoError",
    "OptimizerJsonError",
    "OptimizerSqliteError",
    "OptimizerTomlDecodeError",
    "OutputConfig",
    "PolicyConfig",
    "PolicyType",
    "ProposerDefaults",
    "ProposerError",
    "ProposerConfig",
    "ProposerPromptConfig",
    "RegistryRecord",
    "RunBoard",
    "RunFailedError",
    "RunFailure",
    "RunSettings",
    "SOL_MED_PROPOSER_POLICY_REF",
    "RunState",
    "RunStatus",
    "RunUsage",
    "banking77_eval_policy_ref",
    "gepa_proposer_policy_ref",
    "optimizer_event_log_id",
    "policy_ref",
    "proposer_delta_payload",
    "StateTransitionError",
    "SynthTunnelLease",
    "attach_synth_tunnel_lease",
    "SynthOptimizerError",
    "TasksetSelection",
    "TunnelLease",
    "TunnelError",
    "TunnelLocalTarget",
    "TunnelProvider",
    "UsageRegistrationConfig",
    "ManagedTunnelLease",
    "NgrokTunnelLease",
    "project_run_events",
    "__version__",
    "events_compare",
    "events_replay",
    "gepa_compact_run_storage",
    "gepa_delete_run_storage",
    "gepa_serve",
    "submit_mapo",
    "submit_sft",
    "submit_cispo",
    "submit_ppo",
    "submit_online_reflexion",
    "validate_online_reflexion_evidence_notes",
]
